# Generated by Django 5.2.6 on 2026-04-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='daily_credits_remaining',
            field=models.IntegerField(default=50000),
        ),
    ]
